#!/bin/bash

if [ ! -d /home/git/.ssh ]; then
    mkdir -p /home/git/.ssh
    chmod 700 /home/git/.ssh
fi

if [ ! -f /home/git/.ssh/environment ]; then
    echo "GITEA_CUSTOM=/etc/gitea" >| /home/git/.ssh/environment
    chmod 600 /home/git/.ssh/environment
fi

if [ ! -f /etc/gitea/app.ini ]; then
  if [ ! -f /etc/gitea/conf/app.ini ]; then
    mkdir -p /etc/gitea/

    # Set INSTALL_LOCK to true only if SECRET_KEY is not empty and
    # INSTALL_LOCK is empty
    if [ -n "$SECRET_KEY" ] && [ -z "$INSTALL_LOCK" ]; then
        INSTALL_LOCK=true
    fi

    # Substitude the environment variables in the template
    APP_NAME=${APP_NAME:-"Gitea: Git with a cup of tea"} \
    RUN_MODE=${RUN_MODE:-"dev"} \
    SSH_DOMAIN=${SSH_DOMAIN:-"localhost"} \
    HTTP_PORT=${HTTP_PORT:-"3000"} \
    ROOT_URL=${ROOT_URL:-""} \
    DISABLE_SSH=${DISABLE_SSH:-"false"} \
    SSH_PORT=${SSH_PORT:-"22"} \
    DB_TYPE=${DB_TYPE:-"sqlite3"} \
    DB_HOST=${DB_HOST:-"localhost:3306"} \
    DB_NAME=${DB_NAME:-"gitea"} \
    DB_USER=${DB_USER:-"root"} \
    DB_PASSWD=${DB_PASSWD:-""} \
    DB_PATH=${DB_PATH:-"/var/lib/gitea/gitea.db"} \
    INSTALL_LOCK=${INSTALL_LOCK:-"true"} \
    DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-"false"} \
    REQUIRE_SIGNIN_VIEW=${REQUIRE_SIGNIN_VIEW:-"false"} \
    SECRET_KEY=${SECRET_KEY:-""} \

    envsubst < /etc/templates/app.ini > /etc/gitea/app.ini
  else
    cp /etc/gitea/conf/app.ini /etc/gitea/app.ini
  fi
fi

