# RELEASE.2022-10-24T18-35-07Z is the last version with "fs" (file system) format support, see
# https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html
FROM minio/minio:RELEASE.2022-10-24T18-35-07Z

# Setup ENV for Appstore to be picked up
ENV PKG_MINIO=RELEASE.2022-10-24T18-35-07Z
