# RELEASE.2022-05-26T05-48-41Z is the last version with "fs" (file system) used as default format instead of XL, see
# https://github.com/minio/minio/releases/tag/RELEASE.2022-06-02T02-11-04Z
# and
# https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html
FROM minio/minio:RELEASE.2022-06-17T02-00-35Z

# Setup ENV for Appstore to be picked up
ENV PKG_MINIO=RELEASE.2022-06-17T02-00-35Z
